feat: RegisteredModel.get_estimator supports selecting training method
aliyun/pai-python-sdk pull request #19
Opened 2024-05-17 09:21 UTC by YuZ1225

* RegisteredModel.get_estimator support training methods

2024-05-17 09:35 UTC, pitt-liang reviewed
"support traning method".
PullRequest的title可以更加精确一点。

2024-05-20 02:58 UTC, YuZ1225 commented
> "support traning method". Title for PullRequest could be more clear and informative

update the title

2024-05-20 03:05 UTC, pitt-liang requested changes

2024-05-20 08:07 UTC, YuZ1225 commented on pai/model.py
> +                    f" method: {training_method}."
Updated

2024-05-20 08:10 UTC, pitt-liang approved these changes

2024-05-20 08:11 UTC, pitt-liang approved these changes

2024-05-20 08:11 UTC, merged